#!/bin/zsh


# set dir here
parent_path="/Volumes/PhotoSSD/WEBSITE_Untitled/"

# get current date
current_date=$(date +%Y_%m_%d_%H_%M)

# create sub paths
import_dir=$parent_path"import_images/"
export_dir=$parent_path"finished_images/exports_"$current_date
assets_path=$parent_path"website_repo/assets/"
trash_path=$parent_path"trash/"
jpg_path=$export_dir"/jpg/"
dng_path=$export_dir"/dng/"
img_website_path=$parent_path"website_repo/images/"

# create dirs 
mkdir $export_dir
mkdir $jpg_path
mkdir $dng_path

# for leica M8, lowercase file ext
cd $import_dir
myarray=(`find ./ -maxdepth 1 -name "*.DNG"`)
if [ ${#myarray[@]} -gt 0 ]; then 
    echo "Files from Leica, changing file extension"
    for f in *.DNG; do
        mv "$f" "${f%.DNG}.dng"
    done
else
    echo "Files converted using convert_dngs, keeping current file extension"
fi
sleep 1

# renaming files
cd $import_dir
c=1
for i in $(ls *.dng); do
    int=$RANDOM
    printf -v c_name "%04d" $c
    echo $i $c_name
    mv $i "img_"$c_name"_"$(date +%Y%m%d)"_"$int".dng"
    let c=c+1
    sleep 0.1
done
sleep 1

# add path to applescript
cd $import_dir
sed 's|insert_path_here|set targetFolder to POSIX file "'"$import_dir"'"|g' $assets_path"ExportCameraRawJPGs.SCPT" > $assets_path"ExportCameraRawJPGs_compiled.SCPT"

# execute applescript, this applies the auto camera raw settings to the xmp files
osascript $assets_path"ExportCameraRawJPGs_compiled.SCPT"
sleep 1;

# watch folder img_import_path to make sure all jpgs are ready
cd $import_dir
echo " "
for (( t=1; t<=100; t++ )); do  
    
    echo $t
    
    # get number of files ready
    n_jpgs=$(ls *.jpg | wc -l)
    n_dngs=$(ls *.dng | wc -l)

    if [[ $n_jpgs == $n_dngs ]];then
        echo "jpgs done exporting, moving files"
        sleep 3
        mv *.jpg $jpg_path
        mv *.dng $dng_path
        break
    else
        echo "processing..."
        sleep 1
    fi
    
done

# # add black film like border to images
# cd $jpg_path
# echo " "
# echo "processing jpgs"
# for i in $(ls *.jpg); do
#     echo $i
#     w=$(identify -format "%w" $i)
#     h=$(identify -format "%h" $i)
#     let wc=w-2
#     let hc=h-2

#     lb=$((1+RANDOM%(3-1))).$((RANDOM%999));
#     sb=$((1+RANDOM%(3-1))).$((RANDOM%999));

#     let lbf=lb/10+0.45
#     let sbf=sb/10+0.31
#     echo $lbf $sbf

#     # adding borders, checking if image is landscape or portrait
#     echo "adding black border"
#     if [[ $w > $h ]];then
#         convert $i -gravity Center -crop "$wc"x"$hc"+0+0 img_crop.jpg
#         convert img_crop.jpg -fill gray50 -colorize 100 -bordercolor 'rgb(45,45,45)' -border $sbf%x$lbf% -blur 0x2 burn_edges.png
#         convert burn_edges.png -bordercolor 'rgb(45,45,45)'  -border 1x1 burn_edges.png
#         convert -bordercolor 'rgb(45,45,45)' -border $sbf%x$lbf% $i border_"$i"
#         convert border_"$i" burn_edges.png -compose hardlight -composite border2_"$i"
#     else
#         convert $i -gravity Center -crop "$wc"x"$hc"+0+0 img_crop.jpg
#         convert img_crop.jpg -fill gray50 -colorize 100 -bordercolor 'rgb(45,45,45)' -border $lbf%x$sbf% -blur 0x2 burn_edges.png
#         convert burn_edges.png -bordercolor 'rgb(45),45,45)'  -border 1x1 burn_edges.png
#         convert -bordercolor 'rgb(45,45,45)' -border $lbf%x$sbf% $i border_"$i"
#         convert border_"$i" burn_edges.png -compose hardlight -composite border2_"$i"
#     fi


#     # rotating image 
#     rotate_sample=$((1+RANDOM%(10-1))).$((RANDOM%999));
#     if [[ $rotate_sample > 5 ]];then
#         if [[ $rotate_sample > 8 ]];then
#             echo "rotating image -0.18 degree"
#             convert border2_"$i" -distort SRT -0.18 -gravity center border3_"$i"
#         else
#             echo "rotating image 0.27 degree"
#             convert border2_"$i" -distort SRT 0.27 -gravity center border3_"$i"
#         fi
#     else
#         echo "no rotation applied"
#         cp border2_"$i" border3_"$i"
#     fi

#     rm -rf burn_edges.png img_crop.jpg border_"$i" border2_"$i" $i
#     cp border3_"$i" $i
#     rm -rf border3_"$i"
#     sleep 0.05

# done

# copy images to website repo
cd $jpg_path
cp *.jpg $img_website_path

# export web verions 
cd $img_website_path
echo " "
echo "converting the following images for web:"
ls *.jpg

n=$(ls *.jpg | wc -l); c=1
for i in $(ls *.jpg); do

    # echo process
    echo $c "/" $n ":" $i

    # get img dims
    w=$(identify -format "%w" $i)
    h=$(identify -format "%h" $i)

    cp $i small/
    cp $i medium/

    if [[ $w > $h ]];then
        mogrify -resize 400 small/"$i"
        mogrify -resize 1000 medium/"$i"
        convert small/"$i" small_webp/"${i%%.*}".webp
        #convert medium/"$i" medium_webp/"${i%%.*}".webp
    else
        mogrify -resize 400 small/"$i"
        mogrify -resize 600 medium/"$i"
        convert small/"$i" small_webp/"${i%%.*}".webp
        #convert medium/"$i" medium_webp/"${i%%.*}".webp
    fi

    let c=c+1 

done

# add image data to website
cd $img_website_path
echo " "
echo "creating image data for:"
ls *.jpg

echo "---------------------------------------------"

# Example:
# {'file' : 'file.jpg', 'name' : 'Untitled', 'format' : 'portrait'},
# {'file' : 'file.jpg', 'name' : 'Untitled', 'format' : 'landscape'},

touch new_data.js

for i in $(ls *.jpg); do

    w=$(identify -format "%w" $i)
    h=$(identify -format "%h" $i)

    # echo filename
    filename="${i%.*}"
    echo "$filename"

    if [[ $w > $h ]];then
        echo "              {'file' : '$i', 'name' : 'Untitled', 'format' : 'landscape'}," >> new_data.js
    else
        echo "              {'file' : '$i', 'name' : 'Untitled', 'format' : 'portrait'}," >> new_data.js
    fi

done

# insert data into image-data.js
lineNum="$(grep -n "new data gets automatically inserted above" ../index.html | head -n 1 | cut -d: -f1)"
let lineNum-=3
sed -i.bak "${lineNum}r new_data.js" ../index.html

# remove temp data file 
cd $img_website_path
rm -rf new_data.js

# copy originals to correct folder
mv *.jpg original/
