#!/bin/zsh

# set dir here
parent_path="/Volumes/PhotoSSD/WEBSITE_CNywles/"

# get current date
current_date=$(date +%Y_%m_%d_%H_%M)

# create sub paths
import_dir=$parent_path"import_images/"
export_dir=$import_dir"exports_"$current_date
assets_path=$parent_path"website_repo/assets/"
jpg_path=$export_dir"/jpg/"
tif_path=$export_dir"/tif/"
img_website_path=$parent_path"website_repo/images/"
finalized_path=$parent_path"finished_images/"

# create dirs 
mkdir $export_dir
mkdir $jpg_path
mkdir $tif_path

# move tifs to folder
cd $import_dir
mv *.tif $tif_path

# renaming files
cd $tif_path
c=1
for i in $(ls *.tif); do
    int=$RANDOM
    printf -v c_name "%04d" $c
    echo $i $c_name
    mv $i "img_"$c_name"_"$(date +%Y%m%d)"_"$int".tif"
    let c=c+1
    sleep 0.1
done
sleep 1

# add path to applescript
cd $tif_path
sed 's|insert_path_here|set targetFolder to POSIX file "'"$tif_path"'"|g' $assets_path"ExportCameraRawJPGs.SCPT" > $assets_path"ExportCameraRawJPGs_compiled.SCPT"

# execute applescript, this applies the auto camera raw settings to the xmp files
osascript $assets_path"ExportCameraRawJPGs_compiled.SCPT"
sleep 1;

# watch folder img_import_path to make sure all jpgs are ready
cd $tif_path
echo " "
for (( t=1; t<=100; t++ )); do  
    
    echo $t
    
    # get number of files ready
    n_jpgs=$(ls *.jpg | wc -l)
    n_tifs=$(ls *.tif | wc -l)

    if [[ $n_jpgs == $n_tifs ]];then
        echo "jpgs done exporting, moving files"
        sleep 3
        mv *.jpg $jpg_path
        break
    else
        echo "processing..."
        sleep 1
    fi
    
done

# move "exports_"$current_date to finalized folder
cd $import_dir
mv "exports_"$current_date $finalized_path

# copy images to website repo
cd $finalized_path
cd "exports_"$current_date
cd jpg
cp *.jpg $img_website_path

# export web verions 
cd $img_website_path
echo " "
echo "converting the following images for web:"
ls *.jpg

n=$(ls *.jpg | wc -l); c=1
for i in $(ls *.jpg); do

    # echo process
    echo $c "/" $n ":" $i

    # get img dims
    w=$(identify -format "%w" $i)
    h=$(identify -format "%h" $i)

    cp $i small/
    cp $i medium/
    cp $i large/

    if [[ $w > $h ]];then
        mogrify -resize 400 small/"$i"
        mogrify -resize 1000 medium/"$i"
        convert small/"$i" small_webp/"${i%%.*}".webp
        convert medium/"$i" medium_webp/"${i%%.*}".webp
        convert large/"$i" large_webp/"${i%%.*}".webp
    else
        mogrify -resize 400 small/"$i"
        mogrify -resize 600 medium/"$i"
        convert small/"$i" small_webp/"${i%%.*}".webp
        convert medium/"$i" medium_webp/"${i%%.*}".webp
        convert large/"$i" large_webp/"${i%%.*}".webp
    fi

    let c=c+1 

done

# add image data to website
cd $img_website_path
echo " "
echo "creating image data for:"
ls *.jpg

echo "---------------------------------------------"

# Example:
# {'file' : 'file.jpg', 'name' : 'Untitled', 'format' : 'portrait'},
# {'file' : 'file.jpg', 'name' : 'Untitled', 'format' : 'landscape'},

touch new_data.js

for i in $(ls *.jpg); do

    w=$(identify -format "%w" $i)
    h=$(identify -format "%h" $i)

    # echo filename
    filename="${i%.*}"
    echo "$filename"

    if [[ $w > $h ]];then
        echo "              {'file' : '$i', 'name' : 'Untitled', 'format' : 'landscape'}," >> new_data.js
    else
        echo "              {'file' : '$i', 'name' : 'Untitled', 'format' : 'portrait'}," >> new_data.js
    fi

done

# insert data into image-data.js
lineNum="$(grep -n "new data gets automatically inserted above" ../index.html | head -n 1 | cut -d: -f1)"
let lineNum-=3
sed -i.bak "${lineNum}r new_data.js" ../index.html

# remove temp data file 
cd $img_website_path
rm -rf new_data.js

# copy originals to correct folder
mv *.jpg original/
